name: deploy retype github page
on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  publish:
    name: Publish to branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1
        with:
          branch: docs
          update-branch: true