name: deploy retype github page
on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages-source

jobs:
  publish:
    name: Publish to branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v2.0.0-preview

      - uses: retypeapp/action-github-pages@v2.0.0-preview
        with:
          branch: gh-pages
          update-branch: true